name: Clarive Ant Plugin
description: Ant plugin will allow you to launch Apache Ant commands from a Clarive instance.
version: 1.0
icon: https://github.com/clarive/cla-ant-plugin/public/icon/ant.svg
url: https://github.com/clarive/cla-ant-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-ant-plugin
